#! /usr/bin/python3

import sys

sys.path.append('/usr/share/export-web-sites/')

import ExportWebSites

if __name__=="__main__":
	
	args={}
	args["gui"]=True
	args["server"]="server"
	ls=ExportWebSites.ExportWebSites(args)
